Docs edit
isar/isar pull request #623
Opened 2022-09-03 20:49 UTC by Frostedfox

updated docs for version 3

2022-09-05 20:03 UTC, leisim requested changes
Thank you very much!

2022-09-05 20:03 UTC, leisim commented on docs/docs/contributors.md
> +---
The contributors get updated automatically by the `@all-contributors` bot. This document will get out of sync :/

2022-09-05 20:04 UTC, leisim commented
@all-contributors please add @Frostedfox for docs

2022-09-06 19:43 UTC, Frostedfox commented
pushed corrections

2022-09-06 20:40 UTC, leisim commented
Thanks so much!

2022-09-06 20:41 UTC, merged

2022-09-07 08:01 UTC, cgestes reviewed
a little late and a bit nitpicking :)

(I am eager to switch to the last version of isar :))

2022-09-07 08:01 UTC, cgestes commented on docs/docs/faq.md
> +That highly depends on the your objects, your indexes and which queries you want to run 🙂 everything in the low millions should be fine
missing dot? same on the next sentence?

2022-09-07 08:01 UTC, cgestes commented on docs/docs/dart.md
> +If you want to use Isar database in unit tests or Dart code, call
```call:``` ?